apiVersion: 1
datasources:
  # connect grafana to prometheus for metrics (will add automatic datasources)
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true