global:
  # global scrape frequency, can be overridden by individual jobs.
  scrape_interval: 20s

scrape_configs:
  # Monitor Prometheus itself
  - job_name: prometheus
    scrape_interval: 10s
    static_configs:
      - targets:
          - prometheus:9090
        labels:
          server_name: <client-instance id>
          environment: <production/staging/uat/development>

  - job_name: cadvisor
    scrape_interval: 10s
    static_configs:
      - targets:
          - cadvisor:8080
        labels:
          server_name: <monitoring-server>
          environment: monitoring

      - targets:
          - <BACKEND_CADVISOR_IP1>:8080 
        labels:
          server_name: <backend-server>
          environment: <production/staging/uat/development>

  
  # Node exporter for monitoring server itself
  - job_name: node
    static_configs:
      - targets:
          - node-exporter:9100
        labels:
          server_name: <monitoring-server>
          environment: monitoring

      # Replace this tag with server private IP (Note: If backend and monitoring server are in different VPC, use public IP with restricted SG)
      - targets:
          - <BACKEND_NODE_EXPORTER_IP1>:9100 
        labels:
          server_name: <backend-server>
          environment: <production/staging/uat/development>
        


